name: Push Registry Info to External Repo

on:
  workflow_run:
    workflows: ["Build Docker image and push to Docker hub"]
    types:
      - completed

permissions:
  contents: write
  actions: read

jobs:
  push-registry-info:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: registry-info
          path: .

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.TARGET_REPO_SSH_KEY }}

      - name: Clone target repo and push registry-info.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git clone git@github.com:shapi78/test-repo.git target-repo
          cp registry-info.json target-repo/
          cd target-repo
          git checkout -b lior-branch || git checkout lior-branch
          git add registry-info.json
          git commit -m "Update registry info with new image"
          git push origin lior-branch
